// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type MessageRole string

const (
	MessageRoleUser      MessageRole = "user"
	MessageRoleAssistant MessageRole = "assistant"
)

func (e *MessageRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MessageRole(s)
	case string:
		*e = MessageRole(s)
	default:
		return fmt.Errorf("unsupported scan type for MessageRole: %T", src)
	}
	return nil
}

type NullMessageRole struct {
	MessageRole MessageRole
	Valid       bool // Valid is true if MessageRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMessageRole) Scan(value interface{}) error {
	if value == nil {
		ns.MessageRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MessageRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMessageRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MessageRole), nil
}

type Conversation struct {
	ID        pgtype.UUID
	Title     string
	CreatedAt pgtype.Timestamptz
}

type Message struct {
	ID             pgtype.UUID
	ConversationID pgtype.UUID
	Role           MessageRole
	Content        string
	CreatedAt      pgtype.Timestamptz
}
