// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateConversation(ctx context.Context) (Conversation, error)
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	GetConversation(ctx context.Context, id pgtype.UUID) (Conversation, error)
	ListConversations(ctx context.Context) ([]Conversation, error)
	ListMessages(ctx context.Context, conversationID pgtype.UUID) ([]Message, error)
}

var _ Querier = (*Queries)(nil)
